apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: node-build
spec:
  description: |
    Build NodeJS Projects
  params:
  - name: GIT_REPO
    type: string
  - name: GIT_REVISION
    default: main
  workspaces:
  - name: shared-data
  - name: git-credentials
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
